/// Who's That question bank — copied verbatim from the web game
/// (milkekhelo.com/whosthat.html) so app and web players can share a room:
/// a game stores question *indexes* (`qIdx`), and each device shows the
/// question in its own language. Keep the two lists the same length and
/// order.
class WtQuestions {
  WtQuestions._();

  static const List<String> en = [
    'Who will become the first millionaire in this group?',
    'Who is most likely to start their own business?',
    'Who would spend their whole salary in one day?',
    'Who is the best at saving money?',
    'Who would lend you money without asking why?',
    'Who is most likely to win the lottery and tell nobody?',
    'Who negotiates the hardest while shopping?',
    'Who would forget to pay a bill for months?',
    'Who is the most annoying person here?',
    'Who can keep a secret the best?',
    'Who is the group\'s biggest gossip?',
    'Who is the most competitive?',
    'Who is the most organised?',
    'Who is the most stubborn?',
    'Who is the calmest in a crisis?',
    'Who is the most dramatic?',
    'Who apologises the most?',
    'Who is the most patient?',
    'Who overthinks everything?',
    'Who is the most spontaneous?',
    'Who is always late?',
    'Who spends the most time on their phone?',
    'Who has the messiest room?',
    'Who wakes up the earliest?',
    'Who sleeps the most?',
    'Who drinks the most chai or coffee?',
    'Who checks their phone first thing in the morning?',
    'Who takes the longest to get ready?',
    'Who leaves messages on read the longest?',
    'Who has the most unread emails?',
    'Who gives the best advice?',
    'Who is the best cook?',
    'Who takes the best photos?',
    'Who would win at a trivia night?',
    'Who would win a dance-off?',
    'Who sings the loudest in the car?',
    'Who is best at remembering birthdays?',
    'Who is the best storyteller?',
    'Who is the best at keeping plants alive?',
    'Who could fix something around the house?',
    'Who is most likely to survive a zombie apocalypse?',
    'Who would survive the longest without WiFi?',
    'Who would get lost in their own city?',
    'Who would panic first in an emergency?',
    'Who would you want beside you in a horror movie?',
    'Who would talk their way out of trouble?',
    'Who would last longest stranded on an island?',
    'Who would be the first to try alien food?',
    'Who would you call at 3am in an emergency?',
    'Who makes friends the fastest?',
    'Who gives the best hugs?',
    'Who is the peacemaker of the group?',
    'Who remembers every detail of old conversations?',
    'Who is most likely to plan a surprise party?',
    'Who is the glue that holds this group together?',
    'Who would cancel plans at the last minute?',
    'Who texts the most in the group chat?',
    'Who is most likely to become lifelong friends with everyone here?',
    'Who tells the worst jokes?',
    'Who laughs at their own jokes the most?',
    'Who cries during movies?',
    'Who has the loudest laugh?',
    'Who makes the weirdest facial expressions?',
    'Who talks in their sleep?',
    'Who is most likely to trip over nothing?',
    'Who has the most embarrassing story?',
    'Who is most likely to become famous?',
    'Who is most likely to move abroad?',
    'Who is most likely to become a teacher?',
    'Who will have the most kids?',
    'Who is most likely to write a book?',
    'Who is most likely to run a marathon?',
    'Who is most likely to appear on TV?',
    'Who is most likely to become a politician?',
    'Who is most likely to retire early?',
    'Who is most likely to go viral online?',
    'Who is the biggest foodie?',
    'Who is the pickiest eater?',
    'Who would eat the same meal every day?',
    'Who orders dessert first?',
    'Who is most likely to try the spiciest dish?',
    'Who takes photos of their food?',
    'Who is most likely to become a vegetarian?',
    'Who always finishes everyone else\'s leftovers?',
    'Who plans the best trips?',
    'Who would forget their passport at home?',
    'Who packs the heaviest suitcase?',
    'Who is most likely to travel solo?',
    'Who would go bungee jumping first?',
    'Who takes the most photos on holiday?',
    'Who would miss their flight?',
    'Who would adopt ten pets?',
    'Who is the worst driver?',
    'Who would forget their own birthday?',
    'Who is most likely to win an argument?',
    'Who would survive a week without their phone?',
    'Who is the most superstitious?',
    'Who believes in ghosts the most?',
    'Who would be the last to leave a party?',
    'Who is most likely to fall asleep in a movie?',
    'Who has the best taste in music?',
    'Who is most likely to start a random new hobby?',
    'Who would be the best team captain?',
    'Who leaves the most tabs open on their phone?',
    'Who forgets where they kept their keys the most?',
    'Who takes the longest showers?',
    'Who is most likely to burn toast?',
    'Who hits snooze the most times?',
    'Who talks the most while watching a movie?',
    'Who is most likely to lose their charger?',
    'Who has the most apps on their phone?',
    'Who forgets to reply to messages the most?',
    'Who is most likely to leave the house without their wallet?',
    'Who spends the longest choosing what to watch?',
    'Who is most likely to double-text?',
    'Who takes the most screenshots?',
    'Who has the lowest phone battery right now?',
    'Who is most likely to forget an anniversary?',
    'Who reuses the same password everywhere?',
    'Who is most likely to leave dishes in the sink?',
    'Who talks to themselves the most?',
    'Who is the last to know the latest news?',
    'Who is most likely to fall for a scam call?',
    'Who is the mom of the friend group?',
    'Who gives the most unsolicited advice?',
    'Who is most likely to start a group chat?',
    'Who leaves the group chat on mute?',
    'Who is the first to arrive at a party?',
    'Who knows everyone\'s secrets?',
    'Who is most likely to reconnect with an old friend?',
    'Who is the hardest to make plans with?',
    'Who always picks the restaurant?',
    'Who is most likely to organise a reunion?',
    'Who gives the most thoughtful gifts?',
    'Who is the loudest in the group?',
    'Who is the quietest until you know them?',
    'Who is most likely to befriend a stranger?',
    'Who is the group therapist?',
    'Who is most likely to cry at a wedding?',
    'Who is the first to hit the dance floor?',
    'Who is the group\'s designated photographer?',
    'Who is most likely to become their own boss?',
    'Who works the hardest?',
    'Who is most likely to get promoted first?',
    'Who is most likely to change careers?',
    'Who takes the most coffee breaks?',
    'Who is most likely to work on a holiday?',
    'Who is the most creative?',
    'Who is most likely to invent something?',
    'Who is the best public speaker?',
    'Who is most likely to give a TED talk?',
    'Who is the most tech-savvy?',
    'Who is most likely to start a side hustle?',
    'Who negotiates the best salary?',
    'Who is the most ambitious?',
    'Who is the biggest perfectionist?',
    'Who is most likely to procrastinate a deadline?',
    'Who is the best at multitasking?',
    'Who is the most optimistic?',
    'Who is the most sarcastic?',
    'Who is the most sensitive?',
    'Who is the most fearless?',
    'Who is the most easily distracted?',
    'Who is the most generous?',
    'Who is the most curious?',
    'Who is the hardest to impress?',
    'Who is the most easygoing?',
    'Who holds a grudge the longest?',
    'Who forgives the fastest?',
    'Who is the most honest?',
    'Who is the best listener?',
    'Who is the most impulsive?',
    'Who is the most confident?',
    'Who is the most humble?',
    'Who is the most loyal?',
    'Who would survive the longest in the wild?',
    'Who would win a staring contest?',
    'Who would spend the most at a claw machine?',
    'Who would talk to animals if they could?',
    'Who would win in a game of hide and seek?',
    'Who would be the first voted off a reality show?',
    'Who would survive the longest in a haunted house?',
    'Who would eat dessert before dinner?',
    'Who would win a hot-dog eating contest?',
    'Who would be the best game show host?',
    'Who would survive a week in complete silence?',
    'Who would be the last one awake at a sleepover?',
    'Who would make the best detective?',
    'Who would be the worst at lying?',
    'Who is most likely to travel the world?',
    'Who would forget their sunscreen?',
    'Who plans every minute of a trip?',
    'Who would rather have no plan at all?',
    'Who is most likely to miss the bus?',
    'Who packs snacks for every journey?',
    'Who is most likely to try skydiving?',
    'Who takes the most souvenirs home?',
    'Who would haggle at every market?',
    'Who gets lost the easiest?',
    'Who is the best navigator?',
    'Who prefers a beach over the mountains?',
    'Who is the most enthusiastic tourist?',
    'Who would try every street food?',
    'Who books everything at the last minute?',
    'Who is the best home cook?',
    'Who burns water while cooking?',
    'Who has the biggest sweet tooth?',
    'Who orders the most takeout?',
    'Who is the pickiest about coffee?',
    'Who eats the spiciest food?',
    'Who is most likely to bake for the group?',
    'Who never shares their fries?',
    'Who tries every new cafe first?',
    'Who is the fussiest eater?',
    'Who is most likely to start a diet on Monday?',
    'Who drinks the most water?',
    'Who has the messiest fridge?',
    'Who finishes everyone\'s leftovers?',
    'Who is the master of instant noodles?',
    'Who has the most photos on their phone?',
    'Who binge-watches an entire series overnight?',
    'Who has the best music taste?',
    'Who still uses an ancient phone?',
    'Who is the biggest gamer?',
    'Who knows the most movie trivia?',
    'Who is most likely to start a podcast?',
    'Who is always first to try a new app?',
    'Who spends the most time on social media?',
    'Who takes the best selfies?',
    'Who is the worst at texting back?',
    'Who quotes movies the most?',
    'Who is most likely to win a karaoke night?',
    'Who is most likely to break their phone screen?',
    'Who watches the same movie a hundred times?',
    'Who is the biggest spender?',
    'Who is the best at saving?',
    'Who lends money and never asks for it back?',
    'Who is the most generous tipper?',
    'Who tracks every rupee they spend?',
    'Who is most likely to splurge on a whim?',
    'Who hunts for the best deals?',
    'Who forgets to pay people back?',
    'Who would blow their savings on a trip?',
    'Who is the most careful with money?',
    'Who spends the most on clothes?',
    'Who is most likely to fall for a sale?',
    'Who is the biggest flirt?',
    'Who is the most romantic?',
    'Who is most likely to plan a surprise date?',
    'Who falls in love the fastest?',
    'Who is the shyest around a crush?',
    'Who remembers every important date?',
    'Who laughs at the wrong moments?',
    'Who has the most contagious laugh?',
    'Who makes the best impressions?',
    'Who is the clumsiest?',
    'Who tells the longest stories?',
    'Who is most likely to trip in public?',
    'Who sings in the shower the loudest?',
    'Who is the most ticklish?',
    'Who has the most random facts memorised?',
    'Who is the worst at keeping a straight face?',
    'Who is most likely to start dancing anywhere?',
    'Who has the most dramatic reactions?',
    'Who is the best at charades?',
    'Who is the most competitive at board games?',
    'Who is the sorest loser?',
    'Who is most likely to cheat at cards?',
    'Who gives the wisest advice?',
    'Who stays calm under pressure?',
    'Who is the bravest?',
    'Who is the best problem solver?',
    'Who is the most reliable?',
    'Who would you trust with a secret?',
    'Who is the kindest to strangers?',
    'Who steps up in a crisis?',
    'Who is the most disciplined?',
    'Who never gives up?',
    'Who is the most inspiring?',
  ];

  static const List<String> hi = [
    'इस ग्रुप में सबसे पहले करोड़पति कौन बनेगा?',
    'अपना खुद का बिज़नेस शुरू करने की सबसे ज़्यादा संभावना किसकी है?',
    'पूरी सैलरी एक ही दिन में कौन खर्च कर देगा?',
    'पैसे बचाने में सबसे अच्छा कौन है?',
    'बिना वजह पूछे आपको पैसे कौन उधार देगा?',
    'लॉटरी जीतकर किसी को न बताने वाला कौन होगा?',
    'शॉपिंग में सबसे ज़्यादा मोल-भाव कौन करता है?',
    'महीनों तक बिल भरना कौन भूल जाएगा?',
    'यहाँ सबसे ज़्यादा परेशान करने वाला कौन है?',
    'राज़ सबसे अच्छे से कौन रख सकता है?',
    'ग्रुप का सबसे बड़ा गॉसिप किंग या क्वीन कौन है?',
    'सबसे ज़्यादा कॉम्पिटिटिव कौन है?',
    'सबसे ज़्यादा व्यवस्थित कौन है?',
    'सबसे ज़्यादा ज़िद्दी कौन है?',
    'मुश्किल घड़ी में सबसे शांत कौन रहता है?',
    'सबसे ज़्यादा ड्रामेबाज़ कौन है?',
    'सबसे ज़्यादा माफ़ी कौन माँगता है?',
    'सबसे ज़्यादा धैर्य किसमें है?',
    'हर बात पर ज़्यादा सोचने वाला कौन है?',
    'सबसे ज़्यादा बेफ़िक्र कौन है?',
    'हमेशा लेट कौन आता है?',
    'फ़ोन पर सबसे ज़्यादा समय कौन बिताता है?',
    'सबसे गंदा कमरा किसका है?',
    'सबसे जल्दी कौन उठता है?',
    'सबसे ज़्यादा कौन सोता है?',
    'सबसे ज़्यादा चाय या कॉफ़ी कौन पीता है?',
    'सुबह उठते ही फ़ोन कौन देखता है?',
    'तैयार होने में सबसे ज़्यादा समय कौन लेता है?',
    'मैसेज पढ़कर सबसे देर से जवाब कौन देता है?',
    'सबसे ज़्यादा अनरीड ईमेल किसके हैं?',
    'सबसे अच्छी सलाह कौन देता है?',
    'सबसे अच्छा खाना कौन बनाता है?',
    'सबसे अच्छी फ़ोटो कौन खींचता है?',
    'ट्रिविया नाइट में कौन जीतेगा?',
    'डांस मुक़ाबले में कौन जीतेगा?',
    'गाड़ी में सबसे ज़ोर से कौन गाता है?',
    'जन्मदिन याद रखने में सबसे अच्छा कौन है?',
    'सबसे अच्छा किस्सा कौन सुनाता है?',
    'पौधों को ज़िंदा रखने में सबसे अच्छा कौन है?',
    'घर की टूटी चीज़ कौन ठीक कर सकता है?',
    'ज़ॉम्बी अपोकैलिप्स में सबसे ज़्यादा कौन बचेगा?',
    'बिना वाई-फ़ाई सबसे ज़्यादा कौन रह सकता है?',
    'अपने ही शहर में कौन खो जाएगा?',
    'इमरजेंसी में सबसे पहले कौन घबराएगा?',
    'हॉरर फ़िल्म में आप किसे साथ चाहेंगे?',
    'बातों से मुसीबत से कौन निकल जाएगा?',
    'सुनसान द्वीप पर सबसे ज़्यादा कौन टिकेगा?',
    'एलियन का खाना सबसे पहले कौन चखेगा?',
    'रात 3 बजे इमरजेंसी में आप किसे कॉल करेंगे?',
    'सबसे जल्दी दोस्त कौन बनाता है?',
    'सबसे अच्छी झप्पी कौन देता है?',
    'ग्रुप का शांति दूत कौन है?',
    'पुरानी बातें हर डिटेल के साथ कौन याद रखता है?',
    'सरप्राइज़ पार्टी प्लान करने की संभावना किसकी है?',
    'इस ग्रुप को जोड़कर कौन रखता है?',
    'आख़िरी वक़्त पर प्लान कौन कैंसिल करेगा?',
    'ग्रुप चैट में सबसे ज़्यादा कौन लिखता है?',
    'यहाँ सबसे लंबी दोस्ती किसकी रहेगी?',
    'सबसे घटिया चुटकुले कौन सुनाता है?',
    'अपने ही चुटकुलों पर सबसे ज़्यादा कौन हँसता है?',
    'फ़िल्मों में कौन रोता है?',
    'सबसे ज़ोरदार हँसी किसकी है?',
    'सबसे अजीब चेहरे कौन बनाता है?',
    'नींद में कौन बड़बड़ाता है?',
    'बिना किसी वजह के कौन गिर सकता है?',
    'सबसे शर्मनाक किस्सा किसका है?',
    'मशहूर होने की सबसे ज़्यादा संभावना किसकी है?',
    'विदेश जाने की सबसे ज़्यादा संभावना किसकी है?',
    'टीचर बनने की संभावना किसकी है?',
    'सबसे ज़्यादा बच्चे किसके होंगे?',
    'किताब लिखने की संभावना किसकी है?',
    'मैराथन दौड़ने की संभावना किसकी है?',
    'टीवी पर आने की संभावना किसकी है?',
    'नेता बनने की संभावना किसकी है?',
    'जल्दी रिटायर होने की संभावना किसकी है?',
    'ऑनलाइन वायरल होने की संभावना किसकी है?',
    'सबसे बड़ा खाने का शौकीन कौन है?',
    'सबसे नखरे वाला खाने में कौन है?',
    'रोज़ एक ही खाना कौन खा सकता है?',
    'सबसे पहले मिठाई कौन ऑर्डर करता है?',
    'सबसे तीखा खाना कौन चखेगा?',
    'खाने की फ़ोटो कौन खींचता है?',
    'शाकाहारी बनने की संभावना किसकी है?',
    'सबका बचा खाना कौन खत्म करता है?',
    'सबसे अच्छी ट्रिप कौन प्लान करता है?',
    'पासपोर्ट घर पर कौन भूल जाएगा?',
    'सबसे भारी सूटकेस कौन पैक करता है?',
    'अकेले घूमने की संभावना किसकी है?',
    'बंजी जंपिंग सबसे पहले कौन करेगा?',
    'छुट्टियों में सबसे ज़्यादा फ़ोटो कौन खींचता है?',
    'फ़्लाइट कौन मिस करेगा?',
    'दस पालतू जानवर कौन पाल लेगा?',
    'सबसे ख़राब ड्राइवर कौन है?',
    'अपना ही जन्मदिन कौन भूल जाएगा?',
    'बहस जीतने की सबसे ज़्यादा संभावना किसकी है?',
    'बिना फ़ोन एक हफ़्ता कौन रह सकता है?',
    'सबसे ज़्यादा अंधविश्वासी कौन है?',
    'भूतों पर सबसे ज़्यादा कौन यक़ीन करता है?',
    'पार्टी से सबसे आख़िर में कौन निकलेगा?',
    'फ़िल्म देखते हुए कौन सो जाएगा?',
    'सबसे अच्छा म्यूज़िक टेस्ट किसका है?',
    'अचानक नया शौक कौन शुरू कर देगा?',
    'सबसे अच्छा टीम कैप्टन कौन बनेगा?',
    'फोन पर सबसे ज़्यादा टैब कौन खुले रखता है?',
    'चाबियां कहां रखीं, सबसे ज़्यादा कौन भूलता है?',
    'सबसे लंबा नहाने वाला कौन है?',
    'टोस्ट जलाने की संभावना किसकी है?',
    'अलार्म का स्नूज़ सबसे ज़्यादा कौन दबाता है?',
    'फिल्म देखते हुए सबसे ज़्यादा कौन बोलता है?',
    'चार्जर खोने की संभावना किसकी है?',
    'फोन में सबसे ज़्यादा ऐप किसके हैं?',
    'मैसेज का जवाब देना सबसे ज़्यादा कौन भूलता है?',
    'बटुआ घर छोड़कर निकलने की संभावना किसकी है?',
    'क्या देखें, तय करने में सबसे ज़्यादा समय कौन लेता है?',
    'बिना जवाब आए दोबारा मैसेज कौन करता है?',
    'सबसे ज़्यादा स्क्रीनशॉट कौन लेता है?',
    'अभी सबसे कम फोन बैटरी किसकी है?',
    'सालगिरह भूलने की संभावना किसकी है?',
    'हर जगह एक ही पासवर्ड कौन इस्तेमाल करता है?',
    'सिंक में बर्तन छोड़ने की संभावना किसकी है?',
    'खुद से सबसे ज़्यादा कौन बात करता है?',
    'ताज़ा खबर सबसे आखिर में किसे पता चलती है?',
    'फर्जी कॉल के झांसे में आने की संभावना किसकी है?',
    'दोस्तों के ग्रुप की \'मां\' कौन है?',
    'बिना मांगे सबसे ज़्यादा सलाह कौन देता है?',
    'ग्रुप चैट शुरू करने की संभावना किसकी है?',
    'ग्रुप चैट को म्यूट कौन रखता है?',
    'पार्टी में सबसे पहले कौन पहुंचता है?',
    'सबके राज़ किसे पता होते हैं?',
    'पुराने दोस्त से दोबारा जुड़ने की संभावना किसकी है?',
    'किसके साथ प्लान बनाना सबसे मुश्किल है?',
    'रेस्तरां हमेशा कौन चुनता है?',
    'रीयूनियन आयोजित करने की संभावना किसकी है?',
    'सबसे सोच-समझकर तोहफे कौन देता है?',
    'ग्रुप में सबसे तेज़ आवाज़ किसकी है?',
    'जान-पहचान होने तक सबसे शांत कौन रहता है?',
    'अजनबी से दोस्ती करने की संभावना किसकी है?',
    'ग्रुप का \'थेरेपिस्ट\' कौन है?',
    'शादी में रोने की संभावना किसकी है?',
    'डांस फ्लोर पर सबसे पहले कौन जाता है?',
    'ग्रुप का तय फोटोग्राफर कौन है?',
    'अपना खुद का बॉस बनने की संभावना किसकी है?',
    'सबसे ज़्यादा मेहनत कौन करता है?',
    'सबसे पहले प्रमोशन पाने की संभावना किसकी है?',
    'करियर बदलने की संभावना किसकी है?',
    'सबसे ज़्यादा कॉफी ब्रेक कौन लेता है?',
    'छुट्टी के दिन काम करने की संभावना किसकी है?',
    'सबसे ज़्यादा रचनात्मक कौन है?',
    'कुछ नया आविष्कार करने की संभावना किसकी है?',
    'सबसे अच्छा वक्ता कौन है?',
    'TED टॉक देने की संभावना किसकी है?',
    'सबसे ज़्यादा टेक-जानकार कौन है?',
    'साइड बिज़नेस शुरू करने की संभावना किसकी है?',
    'सबसे अच्छी सैलरी कौन तय करवा लेता है?',
    'सबसे महत्वाकांक्षी कौन है?',
    'सबसे बड़ा परफेक्शनिस्ट कौन है?',
    'काम टालने की संभावना किसकी है?',
    'एक साथ कई काम करने में सबसे अच्छा कौन है?',
    'सबसे ज़्यादा आशावादी कौन है?',
    'सबसे ज़्यादा व्यंग्य करने वाला कौन है?',
    'सबसे भावुक कौन है?',
    'सबसे निडर कौन है?',
    'सबसे जल्दी ध्यान भटकने वाला कौन है?',
    'सबसे उदार कौन है?',
    'सबसे जिज्ञासु कौन है?',
    'किसे प्रभावित करना सबसे मुश्किल है?',
    'सबसे सहज-सरल कौन है?',
    'सबसे लंबे समय तक नाराज़गी कौन रखता है?',
    'सबसे जल्दी माफ कौन करता है?',
    'सबसे ईमानदार कौन है?',
    'सबसे अच्छा श्रोता कौन है?',
    'सबसे आवेगी कौन है?',
    'सबसे आत्मविश्वासी कौन है?',
    'सबसे विनम्र कौन है?',
    'सबसे वफादार कौन है?',
    'जंगल में सबसे ज़्यादा कौन ज़िंदा रहेगा?',
    'घूरने के मुकाबले में कौन जीतेगा?',
    'क्लॉ मशीन पर सबसे ज़्यादा पैसे कौन लगाएगा?',
    'अगर मुमकिन हो तो जानवरों से कौन बात करेगा?',
    'लुका-छिपी में कौन जीतेगा?',
    'रियलिटी शो से सबसे पहले कौन बाहर होगा?',
    'भूतिया घर में सबसे ज़्यादा कौन टिकेगा?',
    'खाने से पहले मिठाई कौन खाएगा?',
    'हॉट-डॉग खाने की प्रतियोगिता कौन जीतेगा?',
    'सबसे अच्छा गेम शो होस्ट कौन बनेगा?',
    'पूरे हफ्ते चुप्पी में कौन रह पाएगा?',
    'स्लीपओवर में सबसे आखिर तक कौन जागेगा?',
    'सबसे अच्छा जासूस कौन बनेगा?',
    'झूठ बोलने में सबसे खराब कौन होगा?',
    'दुनिया घूमने की संभावना किसकी है?',
    'सनस्क्रीन कौन भूल जाएगा?',
    'ट्रिप का हर मिनट कौन प्लान करता है?',
    'बिना किसी प्लान के कौन रहना पसंद करेगा?',
    'बस छूटने की संभावना किसकी है?',
    'हर सफर के लिए स्नैक्स कौन पैक करता है?',
    'स्काईडाइविंग करने की संभावना किसकी है?',
    'सबसे ज़्यादा सोवेनियर घर कौन लाता है?',
    'हर बाज़ार में मोल-भाव कौन करेगा?',
    'सबसे आसानी से कौन खो जाता है?',
    'सबसे अच्छा रास्ता बताने वाला कौन है?',
    'पहाड़ों से ज़्यादा बीच किसे पसंद है?',
    'सबसे उत्साही पर्यटक कौन है?',
    'हर स्ट्रीट फूड कौन चखेगा?',
    'सब कुछ आखिरी वक्त पर कौन बुक करता है?',
    'सबसे अच्छा घर का खाना कौन बनाता है?',
    'खाना बनाते हुए पानी तक कौन जला देता है?',
    'सबसे बड़ा मीठे का शौकीन कौन है?',
    'सबसे ज़्यादा बाहर का खाना कौन मंगाता है?',
    'कॉफी को लेकर सबसे नखरे किसके हैं?',
    'सबसे तीखा खाना कौन खाता है?',
    'ग्रुप के लिए बेकिंग करने की संभावना किसकी है?',
    'अपने फ्राइज़ कभी शेयर न करने वाला कौन है?',
    'हर नया कैफे सबसे पहले कौन आज़माता है?',
    'खाने में सबसे ज़्यादा नखरे किसके हैं?',
    'सोमवार से डाइट शुरू करने की संभावना किसकी है?',
    'सबसे ज़्यादा पानी कौन पीता है?',
    'सबसे बिखरा फ्रिज किसका है?',
    'सबका बचा खाना कौन खत्म करता है?',
    'इंस्टेंट नूडल्स का मास्टर कौन है?',
    'फोन में सबसे ज़्यादा फोटो किसके हैं?',
    'रातभर में पूरी सीरीज़ कौन देख डालता है?',
    'सबसे अच्छा म्यूज़िक टेस्ट किसका है?',
    'अब भी सबसे पुराना फोन कौन इस्तेमाल करता है?',
    'सबसे बड़ा गेमर कौन है?',
    'सबसे ज़्यादा मूवी ट्रिविया किसे पता है?',
    'पॉडकास्ट शुरू करने की संभावना किसकी है?',
    'नया ऐप सबसे पहले कौन आज़माता है?',
    'सोशल मीडिया पर सबसे ज़्यादा समय कौन बिताता है?',
    'सबसे अच्छी सेल्फी कौन लेता है?',
    'टेक्स्ट का जवाब देने में सबसे खराब कौन है?',
    'सबसे ज़्यादा मूवी डायलॉग कौन बोलता है?',
    'कराओके नाइट कौन जीतेगा?',
    'फोन की स्क्रीन तोड़ने की संभावना किसकी है?',
    'एक ही फिल्म सौ बार कौन देखता है?',
    'सबसे बड़ा खर्चीला कौन है?',
    'बचत में सबसे अच्छा कौन है?',
    'पैसे उधार देकर वापस कभी न मांगने वाला कौन है?',
    'सबसे उदार टिप कौन देता है?',
    'हर रुपया कौन हिसाब में रखता है?',
    'अचानक फिज़ूलखर्ची करने की संभावना किसकी है?',
    'सबसे अच्छे डील कौन ढूंढता है?',
    'पैसे लौटाना कौन भूल जाता है?',
    'ट्रिप पर पूरी बचत कौन उड़ा देगा?',
    'पैसों को लेकर सबसे सावधान कौन है?',
    'कपड़ों पर सबसे ज़्यादा कौन खर्च करता है?',
    'सेल के झांसे में आने की संभावना किसकी है?',
    'सबसे बड़ा फ्लर्ट कौन है?',
    'सबसे रोमांटिक कौन है?',
    'सरप्राइज़ डेट प्लान करने की संभावना किसकी है?',
    'सबसे जल्दी प्यार में कौन पड़ता है?',
    'क्रश के सामने सबसे शर्मीला कौन है?',
    'हर ज़रूरी तारीख कौन याद रखता है?',
    'गलत मौके पर कौन हंसता है?',
    'सबसे संक्रामक हंसी किसकी है?',
    'सबसे अच्छी नकल कौन उतारता है?',
    'सबसे फूहड़ कौन है?',
    'सबसे लंबे किस्से कौन सुनाता है?',
    'सार्वजनिक जगह पर गिरने की संभावना किसकी है?',
    'नहाते हुए सबसे ज़ोर से कौन गाता है?',
    'सबसे ज़्यादा गुदगुदी किसे होती है?',
    'सबसे ज़्यादा रैंडम फैक्ट किसे याद हैं?',
    'गंभीर चेहरा बनाए रखने में सबसे खराब कौन है?',
    'कहीं भी डांस शुरू करने की संभावना किसकी है?',
    'सबसे नाटकीय प्रतिक्रिया किसकी होती है?',
    'चारेड्स में सबसे अच्छा कौन है?',
    'बोर्ड गेम में सबसे प्रतिस्पर्धी कौन है?',
    'सबसे बुरा हारने वाला कौन है?',
    'ताश में बेईमानी करने की संभावना किसकी है?',
    'सबसे समझदार सलाह कौन देता है?',
    'दबाव में सबसे शांत कौन रहता है?',
    'सबसे बहादुर कौन है?',
    'सबसे अच्छा समस्या-समाधानकर्ता कौन है?',
    'सबसे भरोसेमंद कौन है?',
    'किसे आप राज़ बता सकते हैं?',
    'अजनबियों के प्रति सबसे दयालु कौन है?',
    'संकट में सबसे आगे कौन आता है?',
    'सबसे अनुशासित कौन है?',
    'कभी हार न मानने वाला कौन है?',
    'सबसे प्रेरणादायक कौन है?',
  ];

  static int get count => en.length;

  static String text(int index, bool hindi) {
    final bank = hindi ? hi : en;
    if (index < 0 || index >= bank.length) return '';
    return bank[index];
  }
}
